"""
This file provides a handy API for exporting your RootSchemaMap to a corresponding file
"""


import os.path


class FileManagement:
    def __init__(self, plugin_registry, file_name, shebang=None, extension=""):
        # setup variables
        self.shebang = shebang
        self.extension = extension
        self.plugin_registry = plugin_registry
        self.file_name = file_name
        self.lines = ['"""\n', 'This file was automatically generated by sql-fusion\n', '"""\n']

    def add_line(self, line="", indent=0):
        if indent > 0:
            temp = ""
            for x in range(indent):
                temp += "    "
                self.lines.append(temp + line + "\n")
        else:
            self.lines.append(line + "\n")

    # used for imports, appends to top of file
    def add_top_line(self, line=""):
        self.lines.insert(3, line + "\n")

    def add_new_line(self, count=0):
        if count > 0:
            for x in range(count):
                self.lines += "\n"
        else:
            self.lines += "\n"

    def get_lines(self):
        return self.lines

    def save_file(self):
        # try to make build directory
        try:
            os.mkdir("build")
        except FileExistsError:
            pass

        # try to make project directory
        try:
            os.mkdir(os.path.join("build", self.plugin_registry.project_name))
        except FileExistsError:
            pass

        with open(os.path.join("build", self.plugin_registry.project_name, "{0}.{1}".format(self.file_name, self.extension)), "w") as file:
            if self.shebang:
                file.write(self.shebang)
            for line in self.lines:
                file.write(line)
